//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zapupa
{
    using System;
    using System.Collections.Generic;
    
    public partial class IL_PATIO_RESTARAUNT
    {
        public int IL_PATIO_RESTARAUNT1 { get; set; }
        public int PATIO_ADDRESS_ID { get; set; }
        public int WAITER_ID { get; set; }
        public int VISITOR_ID { get; set; }
        public int ITALIAN_MENU_PATIO_ID { get; set; }
        public int JAPANESE_MENU_PATIO_ID { get; set; }
    
        public virtual ITALIAN_MENU_PATIO ITALIAN_MENU_PATIO { get; set; }
        public virtual JAPANESE_MENU_PATIO JAPANESE_MENU_PATIO { get; set; }
        public virtual PATIO_ADDRESS PATIO_ADDRESS { get; set; }
        public virtual VISITOR VISITOR { get; set; }
        public virtual WAITER WAITER { get; set; }
    }
}
