//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zapupa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IL_PATIOEntities1 : DbContext
    {
        public IL_PATIOEntities1()
            : base("name=IL_PATIOEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IL_PATIO_RESTARAUNT> IL_PATIO_RESTARAUNT { get; set; }
        public virtual DbSet<ITALIAN_MENU_PATIO> ITALIAN_MENU_PATIO { get; set; }
        public virtual DbSet<JAPANESE_MENU_PATIO> JAPANESE_MENU_PATIO { get; set; }
        public virtual DbSet<PATIO_ADDRESS> PATIO_ADDRESS { get; set; }
        public virtual DbSet<VISITOR> VISITOR { get; set; }
        public virtual DbSet<WAITER> WAITER { get; set; }
    }
}
