//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zapupa
{
    using System;
    using System.Collections.Generic;
    
    public partial class JAPANESE_MENU_PATIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JAPANESE_MENU_PATIO()
        {
            this.IL_PATIO_RESTARAUNT = new HashSet<IL_PATIO_RESTARAUNT>();
        }
    
        public int ID_JAPANESE_MENU_PATIO { get; set; }
        public string JAPANESE_FOOD_PATIO { get; set; }
        public string JAPANESE_FOOD_PATIO_PRICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IL_PATIO_RESTARAUNT> IL_PATIO_RESTARAUNT { get; set; }
    }
}
